# 競争的環境設定
# 裏切りが有利になりやすい環境での実験用設定

[genetic]
population_size = 60
generations = 1500
mutation_rate = 0.015  # やや高い突然変異率で多様性を確保
elite_count = 3
dna_length = 10

[simulation]
rounds_per_match = 15
default_strategy = "always-defect"  # 競争的戦略をデフォルトに

# 競争的ペイオフ行列
[simulation.payoff_matrix]
reward = 2      # 協力報酬を低く
temptation = 6  # 裏切り誘惑を高く
sucker = 0      # 裏切られると厳しく
punishment = 1  # 両者裏切りでもそれなりの報酬

[output]
report_interval = 150
include_detailed_stats = true

[performance]
parallel_enabled = true

[logging]
level = "info"

[analysis]
convergence_threshold = 0.005  # より厳しい収束判定
convergence_window = 75